---
title: "COVID-19"
author: "Nick Orka"
date: "3/7/2020"
output: 
    html_document:
        fig_width: 9
        fig_height: 6
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
library(readr)
library(leaflet)
library(tidyr)
library(dplyr)
```
## Overview 

This is coronavirus COVID-19 update based on data collected by John Hopkins CSSE.  
https://github.com/CSSEGISandData/COVID-19

```{r, echo=F}
confUrl = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv"

dailyPath <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/"

confDF <- read_csv(confUrl)
lastDate <- max(as.Date(names(confDF)[5:length(confDF)], "%m/%d/%y"))
dateField <- as.character.Date(lastDate, "%m-%d-%Y")

dailyUrl <- paste0(dailyPath, dateField, ".csv")

df <- read_csv(dailyUrl)

df <- df %>%
    mutate(location = sub(", NA", "", paste(`Country/Region`, `Province/State`, sep = ", "))) %>%
    mutate(confPopup = paste0(location, "<br>Confirmed = ", Confirmed,
                              "<br>Deaths = ", Deaths,
                              "<br>Recovered = ", Recovered))

m <- df %>%
    leaflet() %>%
    addTiles() %>%
    #addMarkers(lat = ~Lat, lng = ~Long,
    #           clusterOptions = markerClusterOptions(), popup = confDFAggr$popup) %>%
    addCircleMarkers(lat = ~Latitude, lng = ~Longitude, radius = log(df$Confirmed) + 10,
               clusterOptions = markerClusterOptions(), popup = df$confPopup)

```
## Data for **`r format(lastDate, "%B %d, %Y")`**
```{r, echo=F, cache=T}
m
```